version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Check things are working
          command: |
            echo "they are!"
      - run:
          name: Is there code here?
          command: |
            ls -al
