version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        environment: 
          LC_CTYPE: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US:en
          LC_ALL: en_US.UTF-8
# to mimic env settings from docker file 
    steps:
      - checkout
      - run:
          name: Check things are working
          command: |
            echo "they are!"
      - run:
          name: Is there code here?
          command: |
            ls -al
      - run:
          name: Install OpenMC
          command: |
            echo "Install required packages"
            sudo apt-get --yes update && sudo apt-get --yes upgrade
            sudo apt-get -y install locales
            sudo apt-get --yes install gfortran 
            sudo apt-get --yes install g++ 
            sudo apt-get --yes install cmake 
            sudo apt-get --yes install libhdf5-dev 
            sudo apt-get --yes install git
            sudo apt-get update
            echo "checking for break 1"
            sudo apt-get install -y python3-pip
            echo "checking for break 2"
            sudo apt-get install -y python3-dev
            echo "checking for break 3"
            sudo apt-get install -y python3-setuptools
            echo "checking for break 4"
            sudo apt-get install -y ipython3
            sudo apt-get update
            echo "checking for break 5"
            sudo apt-get install -y python3-tk
            echo "Install unzip"
            sudo apt-get update
            sudo apt-get install -y unzip
            echo "Install optional packages"
            sudo apt-get --yes update
            sudo apt-get --yes install imagemagick
            sudo apt-get --yes install hdf5-tools
            sudo apt-get --yes install paraview
            sudo apt-get --yes install eog
            sudo apt-get --yes install wget
            sudo apt-get --yes install firefox
            sudo apt-get --yes install dpkg
            sudo apt-get --yes install libxkbfile1
            echo "Install optional packages for distributed memory parallel simulations"
            
