version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        environment: 
          LC_CTYPE: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US:en
          LC_ALL: en_US.UTF-8
# to mimic env settings from docker file 
    steps:
      - run:
          name: Show me what is here
          command: | 
          echo hello
      - checkout
      - run:
          name: Is there code here?
          command: |
            ls -al
      - run:
          name: Install OpenMC requirements
          command: |
            echo "=============Install required packages============="
            sudo apt-get --yes update && sudo apt-get --yes upgrade
            sudo apt-get -y install locales
            sudo apt-get --yes install gfortran 
            sudo apt-get --yes install g++ 
            sudo apt-get --yes install cmake 
            sudo apt-get --yes install libhdf5-dev 
            sudo apt-get --yes install git
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo apt-get install -y python3-dev
            sudo apt-get install -y python3-setuptools
            ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
            sudo apt-get install -y ipython3
            sudo apt-get update
            sudo apt-get install -y python3-tk
            echo "=============Install unzip==================="
            sudo apt-get update
            sudo apt-get install -y unzip
            echo "============Install optional packages=========="
            sudo apt-get --yes update
            sudo apt-get --yes install imagemagick
            sudo apt-get --yes install hdf5-tools
            sudo apt-get --yes install paraview
            sudo apt-get --yes install eog
            sudo apt-get --yes install wget
            sudo apt-get --yes install firefox
            sudo apt-get --yes install dpkg
            sudo apt-get --yes install libxkbfile1
            echo "=========Install optional packages for distributed memory parallel simulations========="
            sudo apt install --yes mpich libmpich-dev
            sudo apt install --yes openmpi-bin libopenmpi-dev
            sudo apt-get --yes install libblas-dev 
            sudo apt-get --yes install liblapack-dev
            echo "================Install required Python prerequisites===================="
            sudo pip3 install numpy
            sudo pip3 install pandas
            sudo pip3 install six
            sudo pip3 install h5py
            sudo pip3 install Matplotlib
            sudo pip3 install uncertainties
            sudo pip3 install lxml
            sudo pip3 install scipy
            echo "==================Install optional Python prerequisites===================="
            sudo pip3 install cython
            sudo pip3 install vtk
            sudo apt-get install --yes libsilo-dev
            sudo pip3 install pytest
            sudo pip3 install codecov
            sudo pip3 install pytest-cov
            sudo pip3 install pylint
            echo "===================Install Pyne requirements=================="
            sudo pip3 install tables
            sudo pip3 install setuptools
            sudo pip3 install prettytable
            sudo pip3 install sphinxcontrib_bibtex
            sudo pip3 install numpydoc
            sudo pip3 install nbconvert
            sudo pip3 install nose
            echo "=====================Clone NJOY===================="
            sudo echo -e "Host git@github.com \n StrictHostKeyChecking no" > ~/.ssh/config
            git clone https://github.com/njoy/NJOY2016 /opt/NJOY2016 
            cd /opt/NJOY2016 && mkdir build && cd build && sudo cmake -Dstatic=on .. && make 2>/dev/null && make install
            sudo rm /usr/bin/python
            sudo ln -s /usr/bin/python3 /usr/bin/python
      - run:
          name: Install OpenMC
          command: |
            cd /opt
            echo "==============Build OpenMC====================="
            cp CMakeLists.txt openmc/CMakeLists.txt
            cd openmc && mkdir build && cd build && sudo cmake .. && sudo make && sudo make install
            cd opt/openmc && python3 setup.py develop
            echo"==========Likewise git cloning the plotter will fail, looking for workaround"
            echo "I have finished!"
            
