version: 2.0
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        environment: 
          LC_CTYPE: en_US.UTF-8
          LANG: en_US.UTF-8
          LANGUAGE: en_US:en
          LC_ALL: en_US.UTF-8
# to mimic env settings from docker file 
#
# sudo GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" 
# cd /opt/NJOY/NJOY2016
# if we want to build NJOY
# cd /opt/NJOY/NJOY2016 && sudo mkdir build && cd build && sudo cmake -Dstatic=on .. && make 2>/dev/null && make install
    steps:
      - checkout
      - run:
          name: Move OpenmMC to opt directory, clone MOAB and DAGMC
          command: |
            sudo mkdir /opt/openmc
            sudo cp -r /home/circleci/project/. /opt/openmc
            sudo rm -rf /home/circlci/project
            cd /opt/openmc
            ls -la
            echo 'success if the code is now here'
            sudo echo -e "Host * \n   StrictHostKeyChecking no" > ~/.ssh/config
            sudo mkdir ./MOAB
            sudo chmod 777 ./MOAB
            cd ./MOAB
            git clone -b Version5.1.0 https://bitbucket.org/fathomteam/moab/
            cd .. 
            sudo mv ./MOAB/ /home/MOAB/
            sudo chmod 777 /home/MOAB
            sudo mkdir ./DAGMC
            sudo chmod 777 ./DAGMC
            cd ./DAGMC
            git clone -b develop https://github.com/svalinn/dagmc
            cd ..
            sudo mv ./DAGMC/ /home/DAGMC/
            sudo chmod 777 /home/DAGMC
            ls -la
            sudo apt-get --yes install wget
            cd /home/circleci/project
            mkdir nuclear_data
            cd nuclear_data
            wget https://anl.box.com/shared/static/9igk353zpy8fn9ttvtrqgzvw1vtejoz6.xz
            ls -la
      - run:
          name: Install OpenMC requirements
          command: |
            echo "=============Install required packages============="
            sudo apt-get --yes update && sudo apt-get --yes upgrade
            sudo apt-get -y install locales
            sudo apt-get --yes install cmake
            sudo apt-get --yes install curl
            sudo apt-get --yes install wget
            sudo apt-get --yes install gfortran 
            sudo apt-get --yes install g++ 
            sudo apt-get --yes install libhdf5-dev 
            sudo apt-get --yes install git
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo apt-get install -y python3-dev
            sudo apt-get install -y python3-setuptools
            ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
            sudo apt-get install -y ipython3
            sudo apt-get update
            sudo apt-get install -y python3-tk
            echo "=============Install unzip==================="
            sudo apt-get update
            sudo apt-get install -y unzip
            echo "============Install optional packages=========="
            sudo apt-get --yes update
            sudo apt-get --yes install imagemagick
            sudo apt-get --yes install hdf5-tools
            sudo apt-get --yes install paraview
            sudo apt-get --yes install eog
            sudo apt-get --yes install firefox
            sudo apt-get --yes install dpkg
            sudo apt-get --yes install libxkbfile1
            echo "=========Install optional packages for distributed memory parallel simulations========="
            sudo apt install --yes mpich libmpich-dev
            sudo apt install --yes openmpi-bin libopenmpi-dev
            sudo apt-get --yes install libblas-dev 
            sudo apt-get --yes install liblapack-dev
            echo "================Install required Python prerequisites===================="
            sudo pip3 install numpy
            sudo pip3 install pandas
            sudo pip3 install six
            sudo pip3 install h5py
            sudo pip3 install Matplotlib
            sudo pip3 install uncertainties
            sudo pip3 install lxml
            sudo pip3 install scipy
            echo "==================Install optional Python prerequisites===================="
            sudo pip3 install cython
            sudo pip3 install vtk
            sudo apt-get install --yes libsilo-dev
            sudo pip3 install pytest
            sudo pip3 install codecov
            sudo pip3 install pytest-cov
            sudo pip3 install pylint
            echo "===================Install Pyne requirements=================="
            sudo pip3 install tables
            sudo pip3 install setuptools
            sudo pip3 install prettytable
            sudo pip3 install sphinxcontrib_bibtex
            sudo pip3 install numpydoc
            sudo pip3 install nbconvert
            sudo pip3 install nose
            sudo rm /usr/bin/python
            sudo ln -s /usr/bin/python3 /usr/bin/python
            echo "=====================Build MOAB===================="
            cd /home/MOAB
            sudo mkdir build && cd build
            sudo cmake ../moab -DENABLE_HDF5=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/home/MOAB/
            sudo make -j8 && sudo make -j8 install && sudo cmake ../moab -DBUILD_SHARED_LIBS=OFF && sudo make -j8 install
            echo "=====================Build DAGMC===================="
            cd /home/DAGMC
            sudo mkdir build && cd build
            sudo cmake ../dagmc -DBUILD_TALLY=ON -DCMAKE_INSTALL_PREFIX=/home/DAGMC/ -DMOAB_DIR=/home/MOAB
            sudo make -j8 install
      - run:
          name: Download Nuclear Data Libraries
          command: |
          
      - run:
          name: Install and Build OpenMC
          command: |
            cd /opt/openmc
            echo "==============Build OpenMC====================="
            sudo mkdir build && cd build && sudo cmake -Ddebug=on -Ddagmc=ON -DDAGMC_ROOT=/home/DAGMC/ -DHDF5_PREFER_PARALLEL=OFF .. && sudo make && sudo make install
            cd /opt/openmc && sudo python3 setup.py develop
            echo "==========Likewise git cloning the plotter will fail, looking for workaround"
            echo "I have finished!"
            
